name: Update README Stats

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  workflow_dispatch:  # This allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create or Update README
        run: |
          # Get the latest stats from GitHub API
          echo "Updating README with latest stats..."
          STATS=$(curl -s "https://api.github.com/users/PriyamG2508" | jq -r '. | "## GitHub Stats\n\n- Public Repos: \(.public_repos)\n- Followers: \(.followers)\n- Following: \(.following)"')

          # Check if README.md exists
          if [ ! -f README.md ]; then
            echo "# Welcome to My Profile" > README.md
          fi

          # Append the stats to the README
          echo "$STATS" >> README.md

      - name: Commit changes
        run: |
          git config --local user.email "priyamgupta2508@gmail.com"
          git config --local user.name "Priyam Gupta"
          git add README.md
          git commit -m "Update README stats" || echo "No changes to commit"
          git push
