name: Update README Stats

on:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour
  workflow_dispatch:  # This allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Get the latest stats from GitHub API
          echo "Updating README with latest stats..."
          curl -s "https://api.github.com/users/PriyamG2508" | jq -r '. | "## GitHub Stats\n\n- Public Repos: \(.public_repos)\n- Followers: \(.followers)\n- Following: \(.following)"' > stats.md
          # Append the stats to the README
          cat stats.md >> README.md
          rm stats.md

      - name: Commit changes
        run: |
          git config --local user.email "priyamgupta25-8@gmail.com"
          git config --local user.name "Priyam Gupta"
          git add README.md
          git commit -m "Update README stats" || echo "No changes to commit"
          git push
